---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - spec/
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    checks:
      import/first:
        enabled: false
      import/no-unresolved:
        enabled: false
      import/no-named-default:
        enabled: false
      import/no-named-as-default:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
      import/no-mutable-exports:
        enabled: false
      import/no-amd:
        enabled: false
      import/export:
        enabled: false
      import/no-duplicates:
        enabled: false
      import/no-absolute-path:
        enabled: false
      import/no-dynamic-require:
        enabled: false
      import/no-webpack-loader-syntax:
        enabled: false
    config:
      extensions:
      - .js
      - .jsx
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.json"
  - "**.scss"
exclude_paths:
- config/
- db/
- vendor/
- node_modules/
