language: ruby
dist: trusty
addons:
  postgresql: '9.6'
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without development production"
rvm:
- 2.4.0
notifications:
  email: false
  slack:
    on_failure: change
    secure: lVGPzPmURAUXCvE1GxDVHQUk+3N3MCUBhxsmspwjevkpSzS4ineKKvnLCVkwvwxAZmj+FNIK+Hcy5gizoEP22f0nM7Who2xEL+DIeiVV80LE1nTX+TXdgNozQQ/F85sXQB1sfSdIr4A2JfcD7as+7NkN3EkH3J4qXlQh/TCgIfSBMprlAJJc80cx+X3cVSypGq/ymTtyx+qJoMNy2C7lY6T7gKt3YdYPq2i/rSHPMzvZSu6Swrv//XKtvkBseB9XypMv5fIJppKyOxW31DUMJxbfsSjJR2VTY3tXnuxtAqxnSW2xNJvhY6xW9qEZL+Q5fn1rxjB6CpgmbdGbAGbf9PzgHaQwog74AGWvt8xtcy1ZEsxbHuLXwFMELImWGEXWaVgwCt901plCh1vhnCkTzYiQy94jWPunk1mifzQYX/K1XcgervFuqx+sXXQJNbQLo7LUmCeduYIL3u/3YDxEgwm8/rllOJEH0qJmmxxUTbjZLFa9adjI0N2dLv/1AxHPJKbuJa+ZhT2Lx/FJT9is09eCPi2/vkN9w6zveWvAEcRbIOpJAPGqNfIQtyXTB9VEA9Q4OKhofrSQZJ2dPbSLjEwVbmogd43JEAX0/ficfJjf0C6alpxUJJAuqOPaggKlyveg5GAFK4n+rl3+ftsEhY4yxVGwnefeQ8MN6Vkukus=
before_script:
- bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}
- bundle exec rake db:create db:migrate
script:
- bundle exec rspec spec
