language: ruby

dist: trusty

addons:
  postgresql: '9.6'

cache: bundler

sudo: false

bundler_args: --jobs=3 --retry=3 --without development production

rvm:
  - '2.4.0'

before_script:
  - bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rspec spec
