language: ruby
dist: trusty
addons:
  postgresql: '9.6'
branches:
  only:
  - master
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without development production"
rvm:
- 2.4.0
notifications:
  email: false
  slack:
    rooms:
      secure: X2VvyOob5kLVVBFEYZlQeCIwAIsIP0/m0jGd5kXFPdjpKSrykdvJoJsAFPJbhvNmC3IlFsWGweqVFSWBHgTjmP74vbO3ktRN7shtsFUlHldznnnN9fgMlbu8rvOjpmwOzk3sCmLizKgWpZhOZI8d/bnHQJlK/nLgtfIW1HW3tY+LVgX8qItU0hjFWLKyTeUsTSB9YFzKumrMOmM7+n7bnxtiu9lb3NPOvhd7X/imCHXn7q3e9FAdhiLgBJd/pRpl+F4IVZsiCZuzV4yd0cLnZHlIzhRBTWD6s0rNToxhwlNATRR8tV9IzmwKzAInFPX6Yid9l0cGdmWDOXH/pQgO1cM0tt5r5HV8Brlqvp+m/yx5O/Z61eVvHJctGU5P7g3C480nW5rq5mndFUd4opyxVxaie/aUx7dqw5atoGWHXyomDq+n42UiTydHmXiNlT1GZWu3/U1bUO+Ve/khLEzPGeLf+VPvhxTYd/UkGfe/a2cdNx2qg5n21yp4pZGgYkSOtmcxJ+x7l0OTdf6/PgqzhJzPP83f4IHriIJl2YMOzyWxQD3zo1eUtTyfk2cDCQ6pG1hwtxYGeCftK/lZDMzyxbtHxMnT7BJ9viOEzZhdDyhbPzQH4vKl/OrCQQfQAboLI6/MGoOHPgQqT/trdZCeeaSl6TqGmJuK+n75PSf1ZGE=
    on_success: change
before_script:
- bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}
- bundle exec rake db:create db:migrate
script:
- bundle exec rspec spec
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
